### ISSUE TITLE
Issues on v0.1

### ISSUE THREAD

**Issue by kaizer222** [kaizer222/dino_design_2021#1]
1. Servo will jitter at the limits of specified range, ie. servo will jitter when object is at around 200mm, if keepDistance of 150mm is specified
2. Servo will jitter if object placed in front of sensor is too small. The sensor will have trouble detecting a hand, but will work if an A4 size paper is used.
3. Servo moves violently if object passes by the sensor laterally 
4. while loop takes a lot of loop time. attachInterrupt function recommended for jawServo.

**Comment by yonghuatang** [comment]
Hi I've create a branch `branch-16nov`.

**Comment by yonghuatang** [comment]
Hi 😀

I think that the trouble in detecting hand is the inherent limitation of the HC-SR04 ultrasonic sensor, since it depends on the reflection of acoustic waves by any object it impinges upon.

However, I think the violent movement of the servo when object crossing laterally is fixable, we can do increment e.g. `++posServo`, or write a function that limits the angular velocity.

Could you clarify a little bit about the attachInterrupt function that you've mentioned? Thank you.

James

**Comment by yonghuatang** [comment]
> Hi I've create a branch `branch-16nov`.

I'll create a pull request later, to merge the branch.

**Comment by abbilash29** [comment]
I also have a concern on the LDR/light sensor that we are gonna use for the biting response. I am not sure about the effect of the jaw itself as when we place the light sensor in the mouth, it would be slightly dark and this would result the mouth to close. Therefore, myself and James discussed yesterday and we thought that the physical design is needed so that we can test the light sensor and see the value on serial monitor. After that we can implement the light sensor.

**Comment by kaizer222** [comment]
LDR sensor functions are fixed. Note that manual calibration of ambient light intensity readings are needed for each change in location. Attach interrupt not needed/feasible.
